#!/usr/bin/python
import sys, os, shutil
from os.path import join, isdir, islink, exists

all_files = 'vimrc bashrc vim profile'.split()
home = os.getenv('HOME')
dotfiles = join(home, '.dotfiles')


def die_with_usage():
    print 'Usage examples :'
    print
    print './%s all' % __file__
    print ' -> will replace all your dotfiles'
    print './%s vim bashrc' % __file__
    print ' -> will only replace your .vim and .bashrc'

if __name__ == '__main__':

    to_install = sys.argv[1:]

    if 'all' in to_install:
        to_install = all_files

    print 'Thoses files/directories will be replaced:'
    for f in to_install:
        print '    .%s' % f

    choice = ''
    while choice not in ['yes', 'no']:
        choice = raw_input('Proceed? (yes/no) ')

    if choice == 'no':
        print 'Nothing done.'
        sys.exit()

    for f in to_install:
        path = join(home, '.' + f)
        if exists(path):
            if islink(path):
                os.unlink(path)
            elif isdir(path):
                shutil.rmtree(path)
            else: # file
                os.remove(path)

        # create symlink
        os.symlink(join(dotfiles, f), path)


