#!/usr/bin/python
import sys, os, shutil
from os.path import join, isdir, islink, lexists

all_files = 'vimrc bashrc vim profile tmux.conf'.split()
home = os.getenv('HOME')
dotfiles = join(home, '.dotfiles')


def die_with_usage():
    print 'Usage examples :'
    print
    print '%s all' % __file__
    print ' -> will replace all your dotfiles'
    print '%s vim bashrc' % __file__
    print ' -> will only replace your .vim and .bashrc'
    sys.exit()

if __name__ == '__main__':

    to_install = sys.argv[1:]

    if 'all' in to_install:
        to_install = all_files

    if not to_install:
        die_with_usage()

    print 'Thoses files/directories will be replaced:'
    for f in to_install:
        print '    .%s' % f

    choice = ''
    while choice not in ['yes', 'no']:
        choice = raw_input('Proceed? (yes/no) ')

    if choice == 'no':
        print 'Nothing done.'
        sys.exit()

    for f in to_install:
        path = join(home, '.' + f)
        if lexists(path):
            if islink(path):
                os.unlink(path)
            elif isdir(path):
                shutil.rmtree(path)
            else: # file
                os.remove(path)

        # create symlink
        os.symlink(join(dotfiles, f), path)


